feat: add /health endpoint
Arnauld/jwtd pull request #1
Opened 2022-03-30 12:29 UTC by VincentLim

which should return "OK" with a 200 http status

2022-03-30 12:59 UTC, Arnauld requested changes

2022-03-30 12:59 UTC, Arnauld commented on src/main.rs
> +                    .map(|| "OK");
Any guarantee the http response status code is 200 ?

For the token, I explicitely wrote the `OK` may be something like:

```
warp::reply::with_status(
                "OK".to_string(),
                StatusCode::OK,
            )
```

2022-03-30 13:11 UTC, VincentLim commented on src/main.rs
> +                    .map(|| "OK");
Tests show a return code set to 200.
Explicit is better though.

Passed 'cargo fmt' also :grimacing:

2022-03-30 14:54 UTC, merged

2022-03-31 21:27 UTC, Arnauld commented
`v0.2.5` == `v0.3.1` released and available in docker hub

https://hub.docker.com/layers/jwtd/technbolts/jwtd/v0.2.5/images/sha256-dc832838052279f4ff5531cd3db52d307d16ce0fc16c01d6eec3870ffdcd4efc?context=explore